apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  annotations:
    annotation1: val1
    annotation2: val2
  labels:
    label1: val1
    label2: val2
    system: a
spec:
  containers:
    - name: nginx-container
      image: nginx:1.13
